### ISSUE TITLE
ZookeeperWatcher: @watcher.unsubscribe hangs on ruby 2.2 

### ISSUE THREAD

**Issue by lsjostro** [airbnb/synapse#134]
I found when using ruby 2.2 the watcher doesn't seems to be able to unsubscribe a node. it just hangs here when a node changes:
https://github.com/airbnb/synapse/blob/master/lib/synapse/service_watcher/zookeeper.rb#L87

It's probably a bug with the zk library in combination with ruby 2.2. Seems to work great when using 1.9.3 though.

**Comment by jolynch** [comment]
It appears that the zk library just started running tests on 2.2, and they are currently failing. I am going to close this until the underlying zookeeper library at least claims to work on 2.2.

For now I encourage you to use an older ruby version, and when zk supports 2.2. please do open another issue or comment on this one and I'll take another look.

https://travis-ci.org/zk-ruby/zk

**Comment by jolynch** [comment]
Should be fixed by #138, please let me know if it's not.
