### ISSUE TITLE
[Enhancement] Support Apache Aurora zookeeper service discovery 

### ISSUE THREAD

**Issue by JustinVenus** [airbnb/synapse#147]
Apache Aurora writes information into zookeeper in a slightly different layout than what the zookeeper support in synapse expects.
```javascript
{'additionalEndpoints': {'aurora': {'host': 'mesos-slave03of2.example.com',
                                      'port': 31616},
                          'http': {'host': 'mesos-slave03of2.example.com',
                                    'port': 31616}},
 'serviceEndpoint': {'host': 'mesos-slave03of2.example.com',
                      'port': 31616},
 'shard': 1,
 'status': 'ALIVE'}
```

I'll send a pull request to add the support in a moment.

**Comment by jolynch** [comment]
Might be able to use #104 as a starting point, I believe there are only minor changes to be done there.

**Comment by jolynch** [comment]
I spoke too soon haha. Cheers will follow up in the PR

**Comment by JustinVenus** [comment]
Please see for https://github.com/airbnb/synapse/pull/148 for implementation

**Comment by jolynch** [comment]
I believe this is fixed. Please open a new issues if the `decode` method does not work as expected.
