### ISSUE TITLE
Is synapse must depend on AWS?

### ISSUE THREAD

**Issue by zouyx** [airbnb/synapse#154]
Is synapse must depend on AWS? if i haven't AWS ,can i launch it ?

**Comment by jolynch** [comment]
@zouyx it is a dependency in the gemspec because of the `Ec2TagWatcher`, but if you are not using that watcher then the aws-sdk will just be an unused dependency.

Synapse itself does not depend on running in AWS and can run fine in your own datacenters.

Does that answer your question?

**Comment by jolynch** [comment]
@zouyx I'm going to close this, please reopen with more context if it's still a problem.
