### ISSUE TITLE
 How to auto-detect a brand new service without rewrite the service section in synapse configuration

### ISSUE THREAD

**Issue by PepperYan** [airbnb/synapse#157]
Synapse  is very useful. But I facing some problem when I'm using it.

    Synapse refresh HAProxy config by watching changes on zk. 
    
    when services comes up it update the ha config file. 

     But when I want to add a brand new services that never write in "services" 
     section of Synapse config file.

     How can I update all my Synapse config files in all the servers 
     I maintaining without manually rewrite the configuration?

     Thanks

**Comment by PepperYan** [comment]
Sorry,I did not think it over.Synapse are not responsible to do that.

**Comment by jolynch** [comment]
Hi @PepperYan 

Yes, an external component must supply the list of services to Synapse. We pull from our central service configuration library over in a [cron job](https://github.com/Yelp/synapse-tools/blob/master/src/synapse_tools/configure_synapse.py), which works pretty well.
