### ISSUE TITLE
Synapse and new nodes / auto scaling

### ISSUE THREAD

**Issue by yagnik** [airbnb/synapse#178]
From my understanding so far, we need to restart synapse for it to be aware of new nodes that are added to a service specifically in the case of autoscaling. 
Is there a way we can make synapse aware of new nodes so it automatically reloads ?

**Comment by yagnik** [comment]
I assumed that the watchers will make synapse aware of new nodes and the config will be regenerated but that isn't what I'm seeing in practice.

**Comment by yagnik** [comment]
I'm stupid and a liar, had it misconfigured :(

**Comment by scarletmeow** [comment]
Glad you figured it out. What was your mistake?

**Comment by yagnik** [comment]
I had socket enabled but hadn't given permission to the user to write to the file.
