### ISSUE TITLE
HAProxy with ActiveMQ

### ISSUE THREAD

**Issue by Michal-dia** [airbnb/synapse#187]
Is it possible to configure Synapse to work with activemq?
When creating ActiveMQ Connection what url should I pass? I can't sent the url of the haproxy since it throws an error "connections refuses". 
I didn't fine in the "ReadMe" information on how configure the application itself to the Synapse, only the other side - Synapse to watchers - is described. Can someone please give more information about that?

**Comment by jolynch** [comment]
@Michal-dia If HAProxy can work with activemq then Synapse can manage the HAProxy for you. Can you provide some more detail of your setup?

HAProxy itself has thorough [documentation](https://cbonte.github.io/haproxy-dconv/) which should help you figure out which sections you need. Once you find the sections that you need (frontend, backend, server, etc ...) you can configure those with the Synapse watcher's [haproxy](https://github.com/airbnb/synapse#the-haproxy-section) section.

**Comment by jolynch** [comment]
I'm going to close this because of lack of activity, but feel free to re-open with more context :-)
