### ISSUE TITLE
ZookeeperWatcher does not handle NoNode failures

### ISSUE THREAD

**Issue by jolynch** [airbnb/synapse#205]
There is a race condition in how the ZookeeperWatcher [discovers backends](https://github.com/airbnb/synapse/blob/1edd876513b850cda93fb20d68226c69682973ae/lib/synapse/service_watcher/zookeeper.rb#L129-L130) where we can crash the whole Synapse process if we try to read a node that doesn't exist after the list. For example:

```
E, [2016-08-02T17:02:32.909587 #113325] ERROR -- Synapse::Synapse: synapse: encountered unexpected exception #<ZK::Exceptions::NoNode: inputs: {:path=>"/nerve/..."}> in main thread
```

We've seen this cause stability issues in production, let's catch that NoNode exception and continue.

**Comment by igor47** [comment]
i guess what would happen is synapse would bail and restart. this would force a restart of haproxy which might cause some instability. we've certainly spent a lot of time figuring out how to limit the frequency of haproxy restarts.

i've thought about not restarting haproxy when we boot. but this is not possible. we control a lot of haproxy settings which we don't and can't check for via the stats socket. restarting after writing the config is the only way to be sure that we've probably set random httpcheck options or like shared frontends or queue settings.

**Comment by jolynch** [comment]
cut #206 to mitigate

Interestingly the issue for us was that a few particular Synapse instances kept crashing rather than making it through to configuration, which led to HAProxy having all old backends.

@igor47 Have you guys tried ``state_file_path`` with ``state_file_ttl`` as well as ``restart_interval`` and ``restart_jitter``? Those options were able to get our HAProxy reloads pretty much under control. I think we could limit it even on startup by applying the [jitter logic](https://github.com/airbnb/synapse/blob/master/lib/synapse/haproxy.rb#L1149-L1150) to the init of [@next_restart](https://github.com/airbnb/synapse/blob/master/lib/synapse/haproxy.rb#L829). I think that @solarkennedy mentioned he might be interested in making that change.

**Comment by igor47** [comment]
we use `state_file_path`, and this helps quite a bit. the only case where we restart today is when synapse restarts and when we have to add an entirely new backend.

i was trying to say that i think we *must* restart haproxy when we restart synapse.

**Comment by jolynch** [comment]
I agree the restart on Synapse restart is pretty important. I think the only way we could not restart HAProxy would be to hash the last HAProxy config we ran with and store it in the state file, and force a restart whenever the hash of the last config differs (indicating _something_ changed in the config). At least for us Synapse restarts usually correspond with new services, so we'd have to restart HAProxy anyways ...

#203? haha

I'm closing this issue out now that #206 is merged.
