### ISSUE TITLE
HAProxy configuration is not being updated

### ISSUE THREAD

**Issue by geowa4** [airbnb/synapse#99]
I've spent part of today trying to learn Synapse as I think it could be useful in my infrastructure. I set up a Vagrant box, where I was able to get it to successfully query the AWS API. The issue though was that it never updated the HAProxy configuration. I have committed this learning exercise to [GitHub](https://github.com/geowa4/learn-synapse/commit/7b4cc315ae873303353fbcacfbf8c27e812dc849) so it can be reproduced easily. I've also copied a portion of the README here for coherence.

Reproduction
------------

    vagrant up
    vagrant ssh
    cd /vagrant
    java -jar synapse.jar --config bug.json
    # quit
    cat /etc/haproxy/haproxy.cfg

Synapse clearly indicates via standard out that it has identified the two EC2 instances.
It does not modify /etc/haproxy/haproxy.cfg as configured though it reports that it has regenerated the config.

`synapse.jar` was built with the source at e012cd3a518098545a0ba73958d3c17bd5ab40d9 in airbnb/synapse.

**Comment by jolynch** [comment]
@geowa4 I think you may have run into an issue with the documentation saying options were default to true (do_writes, do_reloads, do_socket) when they were not at the time. On latest master do you still see the issue? Can you paste your config?

I believe I have a fix for MRI installs in #138, but it looks like you're using JRuby?

**Comment by geowa4** [comment]
@jolynch Since this didn't work for me almost a year ago, I decided to use something else. If I have time, I might verify this is fixed, but, honestly, I can't put this too high up on my priority list.

**Comment by jolynch** [comment]
OK, I'm going to close the issue since I think the documentation and code have been fixed. If you come across the problem again please let me know.
